// Replace the contents of server.js with this file.
// Mobile-friendly multiplayer Snake server:
// - Continuous movement (not grid-step movement)
// - Mouse/touch target steering supported by sending {angle}
// - WASD / arrow direction input still supported
// - Red barrier blocks generated by the server
// - Server-side barrier collision
// - Minimap-ready barrier/snake state
// - Rate-limited input validation
// - Socket.IO compatible with the existing frontend

"use strict";

const http = require("http");
const express = require("express");
const { Server } = require("socket.io");

const PORT = Number(process.env.PORT) || 3000;

const app = express();
const httpServer = http.createServer(app);

const io = new Server(httpServer, {
  transports: ["websocket", "polling"],
  pingInterval: 5000,
  pingTimeout: 10000,
  perMessageDeflate: true,
  cors: {
    origin: "*",
    methods: ["GET", "POST"]
  }
});

const CONFIG = Object.freeze({
  WIDTH: 80,
  HEIGHT: 50,

  TICK_RATE: 60,
  LOG_INTERVAL: 5000,

  START_LENGTH: 5,
  MAX_PLAYERS: 32,
  BOT_COUNT: 4,

  BASE_SPEED: 5.4,
  MIN_SPEED: 3.0,
  MAX_SPEED: 9.0,
  TURN_RATE: Math.PI * 5.5,

  BODY_SPACING: 0.58,
  START_RADIUS: 0.42,

  FOOD_COUNT: 10,
  POWERUP_COUNT: 3,

  BARRIER_COUNT: 18,
  BARRIER_MIN_SIZE: 1.2,
  BARRIER_MAX_SIZE: 3.2,

  POWERUP_DURATION: 6000,

  SNAPSHOT_INTERVAL: 50,
  MAX_INPUTS_PER_SECOND: 30,
  MAX_USERNAME_LENGTH: 16
});

const POWER_TYPES = [
  "speed",
  "reverse",
  "multiplier"
];

function performanceNow() {
  return Number(process.hrtime.bigint()) / 1_000_000;
}

function randomInt(max) {
  return Math.floor(Math.random() * max);
}

function randomRange(min, max) {
  return min + Math.random() * (max - min);
}

function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value));
}

function normalizeAngle(angle) {
  while (angle > Math.PI) {
    angle -= Math.PI * 2;
  }

  while (angle < -Math.PI) {
    angle += Math.PI * 2;
  }

  return angle;
}

function angleDelta(from, to) {
  return normalizeAngle(to - from);
}

function cellKey(x, y) {
  return `${Math.floor(x)},${Math.floor(y)}`;
}

function sanitizeUsername(name) {
  return String(name || "Player")
    .replace(/[^\p{L}\p{N}_\- ]/gu, "")
    .trim()
    .slice(0, CONFIG.MAX_USERNAME_LENGTH) || "Player";
}

function validDirection(direction) {
  return [
    "up",
    "down",
    "left",
    "right"
  ].includes(direction);
}

const DIRECTIONS = Object.freeze({
  up: -Math.PI / 2,
  down: Math.PI / 2,
  left: Math.PI,
  right: 0
});

class Snake {
  constructor({
    id,
    username,
    x,
    y,
    angle = 0,
    bot = false
  }) {
    this.id = id;
    this.username = username;
    this.bot = bot;

    this.body = [];

    for (
      let i = 0;
      i < CONFIG.START_LENGTH;
      i++
    ) {
      this.body.push({
        x:
          x -
          Math.cos(angle) *
            CONFIG.BODY_SPACING *
            i,

        y:
          y -
          Math.sin(angle) *
            CONFIG.BODY_SPACING *
            i
      });
    }

    this.angle = angle;
    this.targetAngle = angle;

    this.alive = true;
    this.score = 0;
    this.growthPending = 0;

    this.effects = {
      speed: 0,
      reverse: 0,
      multiplier: 0
    };

    this.lastInputAt = 0;
    this.inputTimes = [];
    this.aiCooldown = 0;
  }

  get head() {
    return this.body[0];
  }

  get speed() {
    const growthBonus = Math.min(
      1.35,
      this.body.length * 0.008
    );

    const speedPowerup =
      this.effects.speed > 0
        ? 1.65
        : 1;

    return (
      clamp(
        CONFIG.BASE_SPEED + growthBonus,
        CONFIG.MIN_SPEED,
        CONFIG.MAX_SPEED
      ) * speedPowerup
    );
  }

  get radius() {
    return (
      CONFIG.START_RADIUS +
      Math.min(
        0.2,
        this.body.length * 0.004
      )
    );
  }

  queueAngle(angle) {
    if (!Number.isFinite(angle)) {
      return;
    }

    const now = performanceNow();

    this.inputTimes =
      this.inputTimes.filter(
        timestamp =>
          now - timestamp < 1000
      );

    if (
      this.inputTimes.length >=
      CONFIG.MAX_INPUTS_PER_SECOND
    ) {
      return;
    }

    this.inputTimes.push(now);

    if (this.effects.reverse > 0) {
      angle = normalizeAngle(
        angle + Math.PI
      );
    }

    this.targetAngle =
      normalizeAngle(angle);

    this.lastInputAt = now;
  }

  queueDirection(direction) {
    if (!validDirection(direction)) {
      return;
    }

    this.queueAngle(
      DIRECTIONS[direction]
    );
  }

  updateEffects(dt) {
    for (const type of POWER_TYPES) {
      if (this.effects[type] > 0) {
        this.effects[type] =
          Math.max(
            0,
            this.effects[type] - dt
          );
      }
    }
  }

  grow(amount = 1) {
    this.growthPending += amount;
  }

  updateAngle(dt) {
    const maxTurn =
      CONFIG.TURN_RATE *
      (dt / 1000);

    const delta = angleDelta(
      this.angle,
      this.targetAngle
    );

    if (
      Math.abs(delta) <=
      maxTurn
    ) {
      this.angle =
        this.targetAngle;
    } else {
      this.angle =
        normalizeAngle(
          this.angle +
            Math.sign(delta) *
              maxTurn
        );
    }
  }

  move(dt) {
    this.updateAngle(dt);

    const moveDistance =
      this.speed *
      (dt / 1000);

    const next = {
      x:
        this.head.x +
        Math.cos(this.angle) *
          moveDistance,

      y:
        this.head.y +
        Math.sin(this.angle) *
          moveDistance
    };

    this.body.unshift(next);

    // Smooth body spacing.
    // This prevents square/grid movement.
    for (
      let i = 1;
      i < this.body.length;
      i++
    ) {
      const previous =
        this.body[i - 1];

      const current =
        this.body[i];

      const dx =
        previous.x -
        current.x;

      const dy =
        previous.y -
        current.y;

      const d =
        Math.hypot(dx, dy);

      if (
        d > CONFIG.BODY_SPACING
      ) {
        const ratio =
          (d -
            CONFIG.BODY_SPACING) /
          d;

        current.x +=
          dx * ratio;

        current.y +=
          dy * ratio;
      }
    }

    if (
      this.growthPending > 0
    ) {
      this.growthPending--;
    } else {
      this.body.pop();
    }
  }

  die() {
    this.alive = false;
  }
}

class SnakeGame {
  constructor() {
    this.players = new Map();
    this.bots = new Map();

    this.food = new Map();
    this.powerups = new Map();

    this.barriers = [];

    this.tickCount = 0;

    this.lastTick =
      performanceNow();

    this.lastSnapshot = 0;
    this.lastLog = 0;

    this.nextEntityId = 1;

    this.previousSnapshot =
      null;

    this.spawnBarriers();
    this.spawnInitialWorld();
    this.createBots();
  }

  generateId(prefix) {
    return `${prefix}_${this.nextEntityId++}`;
  }

  isInside(
    x,
    y,
    margin = 0
  ) {
    return (
      x >= margin &&
      y >= margin &&
      x <=
        CONFIG.WIDTH - margin &&
      y <=
        CONFIG.HEIGHT - margin
    );
  }

  getAllSnakes() {
    return [
      ...this.players.values(),
      ...this.bots.values()
    ];
  }

  barrierHitsCircle(
    x,
    y,
    radius
  ) {
    for (
      const barrier of this.barriers
    ) {
      const closestX =
        clamp(
          x,
          barrier.x,
          barrier.x +
            barrier.width
        );

      const closestY =
        clamp(
          y,
          barrier.y,
          barrier.y +
            barrier.height
        );

      const dx =
        x - closestX;

      const dy =
        y - closestY;

      if (
        dx * dx +
          dy * dy <=
        radius * radius
      ) {
        return true;
      }
    }

    return false;
  }

  barrierHitsPoint(
    x,
    y
  ) {
    return this.barriers.some(
      barrier =>
        x >= barrier.x &&
        x <=
          barrier.x +
            barrier.width &&
        y >= barrier.y &&
        y <=
          barrier.y +
            barrier.height
    );
  }

  spawnBarriers() {
    let attempts = 0;

    while (
      this.barriers.length <
        CONFIG.BARRIER_COUNT &&
      attempts < 5000
    ) {
      attempts++;

      const width =
        randomRange(
          CONFIG.BARRIER_MIN_SIZE,
          CONFIG.BARRIER_MAX_SIZE
        );

      const height =
        randomRange(
          CONFIG.BARRIER_MIN_SIZE,
          CONFIG.BARRIER_MAX_SIZE
        );

      const x =
        randomRange(
          2,
          CONFIG.WIDTH -
            width -
            2
        );

      const y =
        randomRange(
          2,
          CONFIG.HEIGHT -
            height -
            2
        );

      const centerX =
        x + width / 2;

      const centerY =
        y + height / 2;

      // Keep the center relatively open.
      if (
        Math.hypot(
          centerX -
            CONFIG.WIDTH / 2,

          centerY -
            CONFIG.HEIGHT / 2
        ) < 7
      ) {
        continue;
      }

      const overlaps =
        this.barriers.some(
          other =>
            x <
              other.x +
                other.width +
                1 &&

            x +
                width +
                1 >
              other.x &&

            y <
              other.y +
                other.height +
                1 &&

            y +
                height +
                1 >
              other.y
        );

      if (overlaps) {
        continue;
      }

      this.barriers.push({
        id: this.generateId(
          "barrier"
        ),

        x: Number(
          x.toFixed(2)
        ),

        y: Number(
          y.toFixed(2)
        ),

        width: Number(
          width.toFixed(2)
        ),

        height: Number(
          height.toFixed(2)
        )
      });
    }
  }

  getOccupiedCells({
    exclude = null
  } = {}) {
    const occupied =
      new Set();

    for (
      const snake of
        this.getAllSnakes()
    ) {
      if (
        !snake.alive ||
        snake === exclude
      ) {
        continue;
      }

      for (
        const p of snake.body
      ) {
        occupied.add(
          cellKey(
            p.x,
            p.y
          )
        );
      }
    }

    return occupied;
  }

  randomFreeCell() {
    const occupied =
      this.getOccupiedCells();

    for (
      let attempt = 0;
      attempt < 1000;
      attempt++
    ) {
      const x =
        randomRange(
          1,
          CONFIG.WIDTH - 1
        );

      const y =
        randomRange(
          1,
          CONFIG.HEIGHT - 1
        );

      const key =
        cellKey(x, y);

      if (
        occupied.has(key) ||
        this.food.has(key) ||
        this.powerups.has(key) ||
        this.barrierHitsCircle(
          x,
          y,
          0.45
        )
      ) {
        continue;
      }

      return {
        x,
        y
      };
    }

    return null;
  }

  spawnFood() {
    const position =
      this.randomFreeCell();

    if (!position) {
      return;
    }

    const id =
      this.generateId(
        "food"
      );

    this.food.set(
      cellKey(
        position.x,
        position.y
      ),
      {
        id,

        x: Number(
          position.x.toFixed(2)
        ),

        y: Number(
          position.y.toFixed(2)
        )
      }
    );
  }

  spawnPowerup() {
    const position =
      this.randomFreeCell();

    if (!position) {
      return;
    }

    const id =
      this.generateId(
        "power"
      );

    this.powerups.set(
      cellKey(
        position.x,
        position.y
      ),
      {
        id,

        x: Number(
          position.x.toFixed(2)
        ),

        y: Number(
          position.y.toFixed(2)
        ),

        type:
          POWER_TYPES[
            randomInt(
              POWER_TYPES.length
            )
          ]
      }
    );
  }

  spawnInitialWorld() {
    for (
      let i = 0;
      i < CONFIG.FOOD_COUNT;
      i++
    ) {
      this.spawnFood();
    }

    for (
      let i = 0;
      i < CONFIG.POWERUP_COUNT;
      i++
    ) {
      this.spawnPowerup();
    }
  }

  findSpawnPoint() {
    for (
      let attempt = 0;
      attempt < 1500;
      attempt++
    ) {
      const x =
        randomRange(
          5,
          CONFIG.WIDTH - 5
        );

      const y =
        randomRange(
          5,
          CONFIG.HEIGHT - 5
        );

      if (
        this.barrierHitsCircle(
          x,
          y,
          1.4
        )
      ) {
        continue;
      }

      let clear = true;

      for (
        const snake of
          this.getAllSnakes()
      ) {
        if (!snake.alive) {
          continue;
        }

        if (
          Math.hypot(
            x -
              snake.head.x,

            y -
              snake.head.y
          ) < 8
        ) {
          clear = false;
          break;
        }
      }

      if (clear) {
        return {
          x,
          y
        };
      }
    }

    return {
      x: CONFIG.WIDTH / 2,
      y: CONFIG.HEIGHT / 2
    };
  }

  addPlayer(
    socket,
    username
  ) {
    if (
      this.players.size >=
      CONFIG.MAX_PLAYERS
    ) {
      return null;
    }

    const spawn =
      this.findSpawnPoint();

    const snake =
      new Snake({
        id: socket.id,

        username,

        x: spawn.x,

        y: spawn.y,

        angle:
          randomRange(
            -Math.PI,
            Math.PI
          )
      });

    this.players.set(
      socket.id,
      snake
    );

    return snake;
  }

  removePlayer(
    socketId
  ) {
    this.players.delete(
      socketId
    );
  }

  createBots() {
    while (
      this.bots.size <
      CONFIG.BOT_COUNT
    ) {
      const spawn =
        this.findSpawnPoint();

      const id =
        this.generateId(
          "bot"
        );

      const bot =
        new Snake({
          id,

          username:
            `BOT ${
              this.bots.size + 1
            }`,

          x: spawn.x,

          y: spawn.y,

          angle:
            randomRange(
              -Math.PI,
              Math.PI
            ),

          bot: true
        });

      this.bots.set(
        id,
        bot
      );
    }
  }

  resetDeadBots() {
    for (
      const [id, bot] of
        this.bots
    ) {
      if (!bot.alive) {
        const spawn =
          this.findSpawnPoint();

        this.bots.set(
          id,
          new Snake({
            id,

            username:
              bot.username,

            x: spawn.x,

            y: spawn.y,

            angle:
              randomRange(
                -Math.PI,
                Math.PI
              ),

            bot: true
          })
        );
      }
    }
  }

  findNearestFood(
    bot
  ) {
    let closest = null;
    let closestDistance =
      Infinity;

    for (
      const food of
        this.food.values()
    ) {
      const d =
        Math.hypot(
          bot.head.x -
            food.x,

          bot.head.y -
            food.y
        );

      if (
        d < closestDistance
      ) {
        closestDistance = d;
        closest = food;
      }
    }

    return closest;
  }

  chooseBotDirection(
    bot
  ) {
    const target =
      this.findNearestFood(
        bot
      );

    if (!target) {
      return;
    }

    const desired =
      Math.atan2(
        target.y -
          bot.head.y,

        target.x -
          bot.head.x
      );

    const lookAhead = 2.5;

    const tx =
      bot.head.x +
      Math.cos(desired) *
        lookAhead;

    const ty =
      bot.head.y +
      Math.sin(desired) *
        lookAhead;

    if (
      this.isInside(
        tx,
        ty,
        0.5
      ) &&
      !this.barrierHitsCircle(
        tx,
        ty,
        bot.radius
      )
    ) {
      bot.queueAngle(
        desired
      );

      return;
    }

    const candidates = [
      desired +
        Math.PI / 2,

      desired -
        Math.PI / 2,

      desired +
        Math.PI / 3,

      desired -
        Math.PI / 3
    ];

    for (
      const angle of
        candidates
    ) {
      const x =
        bot.head.x +
        Math.cos(angle) *
          lookAhead;

      const y =
        bot.head.y +
        Math.sin(angle) *
          lookAhead;

      if (
        this.isInside(
          x,
          y,
          0.5
        ) &&
        !this.barrierHitsCircle(
          x,
          y,
          bot.radius
        )
      ) {
        bot.queueAngle(
          angle
        );

        return;
      }
    }
  }

  updateBots(dt) {
    for (
      const bot of
        this.bots.values()
    ) {
      if (!bot.alive) {
        continue;
      }

      bot.aiCooldown -= dt;

      if (
        bot.aiCooldown <= 0
      ) {
        this.chooseBotDirection(
          bot
        );

        bot.aiCooldown = 160;
      }
    }
  }

  moveSnakes(dt) {
    for (
      const snake of
        this.getAllSnakes()
    ) {
      if (!snake.alive) {
        continue;
      }

      snake.move(dt);
    }
  }

  resolveCollisions() {
    const snakes =
      this.getAllSnakes();

    const deaths =
      new Set();

    // Wall + barrier collisions.
    for (
      const snake of
        snakes
    ) {
      if (!snake.alive) {
        continue;
      }

      const h =
        snake.head;

      if (
        !this.isInside(
          h.x,
          h.y,
          snake.radius
        ) ||

        this.barrierHitsCircle(
          h.x,
          h.y,
          snake.radius
        )
      ) {
        deaths.add(snake);
      }
    }

    // Self collision.
    for (
      const snake of
        snakes
    ) {
      if (!snake.alive) {
        continue;
      }

      const h =
        snake.head;

      for (
        let i = 6;
        i < snake.body.length;
        i++
      ) {
        const p =
          snake.body[i];

        if (
          Math.hypot(
            p.x -
              h.x,

            p.y -
              h.y
          ) <
          snake.radius *
            1.15
        ) {
          deaths.add(snake);
          break;
        }
      }
    }

    // Head-to-head collisions.
    for (
      let i = 0;
      i < snakes.length;
      i++
    ) {
      const a =
        snakes[i];

      if (!a.alive) {
        continue;
      }

      for (
        let j = i + 1;
        j < snakes.length;
        j++
      ) {
        const b =
          snakes[j];

        if (!b.alive) {
          continue;
        }

        const d =
          Math.hypot(
            a.head.x -
              b.head.x,

            a.head.y -
              b.head.y
          );

        if (
          d <
          (a.radius +
            b.radius) *
            0.9
        ) {
          deaths.add(a);
          deaths.add(b);
        }
      }
    }

    // Head-to-body collisions.
    for (
      const snake of
        snakes
    ) {
      if (!snake.alive) {
        continue;
      }

      for (
        const other of
          snakes
      ) {
        if (
          !other.alive ||
          snake === other
        ) {
          continue;
        }

        for (
          let i = 2;
          i < other.body.length;
          i++
        ) {
          const p =
            other.body[i];

          if (
            Math.hypot(
              p.x -
                snake.head.x,

              p.y -
                snake.head.y
            ) <
            snake.radius *
              0.95
          ) {
            deaths.add(snake);
            break;
          }
        }
      }
    }

    for (
      const snake of
        deaths
    ) {
      snake.die();
    }
  }

  consumeItems() {
    for (
      const snake of
        this.getAllSnakes()
    ) {
      if (!snake.alive) {
        continue;
      }

      const h =
        snake.head;

      for (
        const [key, food] of
          this.food
      ) {
        if (
          Math.hypot(
            h.x -
              food.x,

            h.y -
              food.y
          ) <
          snake.radius +
            0.45
        ) {
          this.food.delete(
            key
          );

          snake.grow(1);

          const multiplier =
            snake.effects
              .multiplier > 0
              ? 2
              : 1;

          snake.score +=
            multiplier;

          this.spawnFood();

          break;
        }
      }

      for (
        const [
          key,
          powerup
        ] of this.powerups
      ) {
        if (
          Math.hypot(
            h.x -
              powerup.x,

            h.y -
              powerup.y
          ) <
          snake.radius +
            0.55
        ) {
          this.powerups.delete(
            key
          );

          snake.effects[
            powerup.type
          ] =
            CONFIG.POWERUP_DURATION;

          break;
        }
      }
    }
  }

  maintainWorld() {
    while (
      this.food.size <
      CONFIG.FOOD_COUNT
    ) {
      this.spawnFood();
    }

    while (
      this.powerups.size <
      CONFIG.POWERUP_COUNT
    ) {
      this.spawnPowerup();
    }

    this.resetDeadBots();
  }

  getLeaderboard() {
    return this.getAllSnakes()
      .map(snake => ({
        id: snake.id,

        username:
          snake.username,

        score:
          snake.score,

        length:
          snake.body.length,

        alive:
          snake.alive,

        bot:
          snake.bot
      }))
      .sort((a, b) => {
        if (
          b.score !==
          a.score
        ) {
          return (
            b.score -
            a.score
          );
        }

        return (
          b.length -
          a.length
        );
      });
  }

  serializeSnake(
    snake
  ) {
    return {
      id: snake.id,

      username:
        snake.username,

      body:
        snake.body.map(
          p => ({
            x: Number(
              p.x.toFixed(3)
            ),

            y: Number(
              p.y.toFixed(3)
            )
          })
        ),

      angle: Number(
        snake.angle.toFixed(4)
      ),

      targetAngle:
        Number(
          snake.targetAngle.toFixed(
            4
          )
        ),

      score:
        snake.score,

      length:
        snake.body.length,

      alive:
        snake.alive,

      bot:
        snake.bot,

      effects: {
        ...snake.effects
      }
    };
  }

  createSnapshot() {
    return {
      tick:
        this.tickCount,

      grid: {
        width:
          CONFIG.WIDTH,

        height:
          CONFIG.HEIGHT
      },

      // The frontend can render these as red blocks.
      barriers:
        this.barriers,

      snakes:
        this.getAllSnakes()
          .filter(
            snake =>
              snake.alive
          )
          .map(
            snake =>
              this.serializeSnake(
                snake
              )
          ),

      food:
        [...this.food.values()],

      powerups:
        [
          ...this.powerups.values()
        ],

      leaderboard:
        this.getLeaderboard()
    };
  }

  createDelta(
    previous,
    current
  ) {
    if (!previous) {
      return {
        full: true,
        state: current
      };
    }

    return {
      full: false,

      tick:
        current.tick,

      barriers:
        current.barriers,

      snakes:
        current.snakes,

      food:
        current.food,

      powerups:
        current.powerups,

      leaderboard:
        current.leaderboard
    };
  }

  broadcastSnapshot(
    force = false
  ) {
    const now =
      performanceNow();

    if (
      !force &&
      now -
        this.lastSnapshot <
        CONFIG.SNAPSHOT_INTERVAL
    ) {
      return;
    }

    this.lastSnapshot = now;

    const snapshot =
      this.createSnapshot();

    const delta =
      this.createDelta(
        this.previousSnapshot,
        snapshot
      );

    io.emit(
      "state",
      delta
    );

    this.previousSnapshot =
      snapshot;
  }

  step(dt) {
    this.tickCount++;

    for (
      const snake of
        this.getAllSnakes()
    ) {
      snake.updateEffects(
        dt
      );
    }

    this.updateBots(dt);

    this.moveSnakes(dt);

    this.resolveCollisions();

    this.consumeItems();

    this.maintainWorld();

    this.broadcastSnapshot();

    const now =
      performanceNow();

    if (
      now -
        this.lastLog >=
      CONFIG.LOG_INTERVAL
    ) {
      this.lastLog = now;

      const activePlayers =
        [
          ...this.players.values()
        ].filter(
          snake =>
            snake.alive
        ).length;

      console.log(
        `[heartbeat] ` +
        `players=${activePlayers}/` +
        `${this.players.size} ` +
        `bots=${this.bots.size} ` +
        `tick=${this.tickCount} ` +
        `food=${this.food.size} ` +
        `powerups=${this.powerups.size} ` +
        `barriers=${this.barriers.length}`
      );
    }
  }
}

const game =
  new SnakeGame();

app.get(
  "/health",
  (_req, res) => {
    res.json({
      ok: true,

      players:
        game.players.size,

      bots:
        game.bots.size,

      tick:
        game.tickCount,

      barriers:
        game.barriers.length,

      uptime:
        process.uptime()
    });
  }
);

app.get(
  "/",
  (_req, res) => {
    res.json({
      ok: true,

      service:
        "snake-arena-server",

      websocket:
        true
    });
  }
);

io.on(
  "connection",
  socket => {
    console.log(
      `[connection] ${socket.id} connected`
    );

    socket.emit(
      "hello",
      {
        grid: {
          width:
            CONFIG.WIDTH,

          height:
            CONFIG.HEIGHT
        },

        barriers:
          game.barriers
      }
    );

    socket.on(
      "join",
      payload => {
        if (
          game.players.has(
            socket.id
          )
        ) {
          return;
        }

        const username =
          sanitizeUsername(
            payload?.username
          );

        const snake =
          game.addPlayer(
            socket,
            username
          );

        if (!snake) {
          socket.emit(
            "joinError",
            {
              message:
                "The arena is currently full."
            }
          );

          return;
        }

        socket.emit(
          "joined",
          {
            id:
              snake.id,

            username:
              snake.username
          }
        );

        game.broadcastSnapshot(
          true
        );

        console.log(
          `[player] ${username} joined ` +
          `(${socket.id}); ` +
          `active=${game.players.size}`
        );
      }
    );

    socket.on(
      "input",
      payload => {
        const snake =
          game.players.get(
            socket.id
          );

        if (
          !snake ||
          !snake.alive ||
          !payload
        ) {
          return;
        }

        // Preferred mobile/mouse input:
        // { angle: radians }
        if (
          typeof payload.angle ===
            "number" &&
          Number.isFinite(
            payload.angle
          )
        ) {
          snake.queueAngle(
            payload.angle
          );

          return;
        }

        // Backwards-compatible:
        // { direction: "up" }
        if (
          typeof payload.direction ===
          "string"
        ) {
          snake.queueDirection(
            payload.direction
          );
        }
      }
    );

    socket.on(
      "disconnect",
      reason => {
        const snake =
          game.players.get(
            socket.id
          );

        if (snake) {
          console.log(
            `[disconnect] ` +
            `${snake.username} ` +
            `(${socket.id}) ` +
            `reason=${reason}`
          );
        }

        game.removePlayer(
          socket.id
        );

        game.broadcastSnapshot(
          true
        );
      }
    );
  }
);

function gameLoop() {
  const now =
    performanceNow();

  let dt =
    now -
    game.lastTick;

  game.lastTick = now;

  // Prevent runaway catch-up
  // after a server stall.
  dt = clamp(
    dt,
    0,
    100
  );

  game.step(dt);

  setImmediate(
    gameLoop
  );
}

httpServer.listen(
  PORT,
  () => {
    console.log(`
╔══════════════════════════════════════════╗
║        MULTIPLAYER SNAKE SERVER          ║
╠══════════════════════════════════════════╣
║ Port: ${String(PORT).padEnd(34)}║
║ Tick: ${String(CONFIG.TICK_RATE + " Hz").padEnd(34)}║
║ Bots: ${String(CONFIG.BOT_COUNT).padEnd(34)}║
║ Barriers: ${String(CONFIG.BARRIER_COUNT).padEnd(30)}║
║ Movement: continuous / mobile-ready      ║
╚══════════════════════════════════════════╝
`);
  }
);

gameLoop();

process.on(
  "SIGINT",
  () => {
    console.log(
      "\nShutting down server..."
    );

    io.close(
      () => {
        httpServer.close(
          () => {
            process.exit(0);
          }
        );
      }
    );
  }
);
